// Imports
import './globals.css';
import { Inter } from 'next/font/google';
import Providers from '@/lib/providers';
import Nav from '@/components/navigation/nav';
import NavLogo from '@/components/navigation/nav-logo';
import NavProfile from '@/components/navigation/nav-profile';
import NavSearch from '@/components/navigation/nav-search';
import "@/utils/env";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Parallel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav search={<NavSearch />} logo={<NavLogo />} profile={<NavProfile />} />
        {children}
        </Providers>
      </body>
    </html>
  )
}
