// Packages
import { Metadata } from 'next';
import { cookies } from 'next/headers';
// Imports
import '@/styles/base/globals.scss';
import Providers from '@/lib/providers';
import { ClientCookiesProvider } from '@/lib/cookies.provider';
import "@/utils/env";

export const metadata: Metadata = {
  title: 'Parallel',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/icon.svg'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/images/icon.svg" sizes='any' />
        <link rel="icon" type="image/png" href="../../public/images/icon.png" sizes='any' />
      </head>

      <body>
        <Providers>
          <ClientCookiesProvider value={cookies().getAll()}>
            {children}
          </ClientCookiesProvider>
        </Providers>
      </body>
    </html>
  )
}
